-- Auto-generated from SQLite by scripts/sqlite_to_supabase.py
-- Target: Supabase Postgres

BEGIN;

CREATE TABLE IF NOT EXISTS public.customers (
  customer_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  full_name TEXT NOT NULL,
  email TEXT NOT NULL,
  gender TEXT NOT NULL,
  birthdate TIMESTAMP NOT NULL,
  created_at TIMESTAMP NOT NULL,
  city TEXT,
  state TEXT,
  zip_code TEXT,
  customer_segment TEXT,
  loyalty_tier TEXT,
  is_active BOOLEAN NOT NULL DEFAULT TRUE,
  UNIQUE (email)
);

CREATE TABLE IF NOT EXISTS public.products (
  product_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  sku TEXT NOT NULL,
  product_name TEXT NOT NULL,
  category TEXT NOT NULL,
  price DOUBLE PRECISION NOT NULL,
  cost DOUBLE PRECISION NOT NULL,
  is_active BOOLEAN NOT NULL DEFAULT TRUE,
  UNIQUE (sku)
);

CREATE TABLE IF NOT EXISTS public.orders (
  order_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  customer_id BIGINT NOT NULL,
  order_datetime TIMESTAMP NOT NULL,
  billing_zip TEXT,
  shipping_zip TEXT,
  shipping_state TEXT,
  payment_method TEXT NOT NULL,
  device_type TEXT NOT NULL,
  ip_country TEXT NOT NULL,
  promo_used BOOLEAN NOT NULL DEFAULT FALSE,
  promo_code TEXT,
  order_subtotal DOUBLE PRECISION NOT NULL,
  shipping_fee DOUBLE PRECISION NOT NULL,
  tax_amount DOUBLE PRECISION NOT NULL,
  order_total DOUBLE PRECISION NOT NULL,
  risk_score DOUBLE PRECISION NOT NULL,
  is_fraud BOOLEAN NOT NULL DEFAULT FALSE,
  FOREIGN KEY (customer_id) REFERENCES public.customers(customer_id)
);

CREATE TABLE IF NOT EXISTS public.product_reviews (
  review_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  customer_id BIGINT NOT NULL,
  product_id BIGINT NOT NULL,
  rating BIGINT NOT NULL,
  review_datetime TIMESTAMP NOT NULL,
  review_text TEXT,
  FOREIGN KEY (product_id) REFERENCES public.products(product_id),
  FOREIGN KEY (customer_id) REFERENCES public.customers(customer_id),
  UNIQUE (customer_id, product_id)
);

CREATE TABLE IF NOT EXISTS public.order_items (
  order_item_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  order_id BIGINT NOT NULL,
  product_id BIGINT NOT NULL,
  quantity BIGINT NOT NULL,
  unit_price DOUBLE PRECISION NOT NULL,
  line_total DOUBLE PRECISION NOT NULL,
  FOREIGN KEY (product_id) REFERENCES public.products(product_id),
  FOREIGN KEY (order_id) REFERENCES public.orders(order_id)
);

CREATE TABLE IF NOT EXISTS public.shipments (
  shipment_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  order_id BIGINT NOT NULL,
  ship_datetime TIMESTAMP NOT NULL,
  carrier TEXT NOT NULL,
  shipping_method TEXT NOT NULL,
  distance_band TEXT NOT NULL,
  promised_days BIGINT NOT NULL,
  actual_days BIGINT NOT NULL,
  late_delivery BOOLEAN NOT NULL DEFAULT FALSE,
  late_delivery_prob DOUBLE PRECISION,
  FOREIGN KEY (order_id) REFERENCES public.orders(order_id),
  UNIQUE (order_id)
);

COMMIT;
