#!/usr/bin/env python3
from __future__ import annotations

import argparse
import sqlite3
from collections import defaultdict, deque
from pathlib import Path


def map_type(column_name: str, sqlite_type: str) -> str:
    name = (column_name or "").strip().lower()
    t = (sqlite_type or "").strip().upper()

    if name.startswith("is_") or name in {"promo_used", "late_delivery"}:
        return "BOOLEAN"
    if name.endswith("_datetime") or name.endswith("_at") or name == "birthdate":
        return "TIMESTAMP"
    if "INT" in t:
        return "BIGINT"
    if any(x in t for x in ("REAL", "FLOA", "DOUB")):
        return "DOUBLE PRECISION"
    if "BLOB" in t:
        return "BYTEA"
    if any(x in t for x in ("TEXT", "CHAR", "CLOB")):
        return "TEXT"
    return "TEXT"


def quote_value(value, as_boolean: bool = False) -> str:
    if value is None:
        return "NULL"
    if as_boolean:
        return "TRUE" if int(value) != 0 else "FALSE"
    if isinstance(value, str):
        return "'" + value.replace("'", "''") + "'"
    return str(value)


def default_expr(raw_default, as_boolean: bool = False) -> str | None:
    if raw_default is None:
        return None

    text = str(raw_default).strip()
    if as_boolean:
        if text in {"0", "(0)"}:
            return "FALSE"
        if text in {"1", "(1)"}:
            return "TRUE"
    return text


def read_tables(conn: sqlite3.Connection) -> list[str]:
    rows = conn.execute(
        "SELECT name FROM sqlite_master WHERE type='table' AND name NOT LIKE 'sqlite_%'"
    ).fetchall()
    return [r[0] for r in rows]


def foreign_keys(conn: sqlite3.Connection, table: str) -> list[dict]:
    fk_rows = conn.execute(f"PRAGMA foreign_key_list({table})").fetchall()
    return [
        {
            "from_col": r[3],
            "ref_table": r[2],
            "ref_col": r[4],
            "on_update": r[5],
            "on_delete": r[6],
        }
        for r in fk_rows
    ]


def ordered_tables(conn: sqlite3.Connection, tables: list[str]) -> list[str]:
    deps = {t: set() for t in tables}
    reverse = defaultdict(set)

    for t in tables:
        for fk in foreign_keys(conn, t):
            ref = fk["ref_table"]
            if ref in deps and ref != t:
                deps[t].add(ref)
                reverse[ref].add(t)

    indegree = {t: len(deps[t]) for t in tables}
    queue = deque(sorted([t for t in tables if indegree[t] == 0]))
    out = []

    while queue:
        t = queue.popleft()
        out.append(t)
        for child in sorted(reverse[t]):
            indegree[child] -= 1
            if indegree[child] == 0:
                queue.append(child)

    # Fall back to alphabetical for any cyclic leftovers (rare in this DB).
    leftovers = sorted([t for t in tables if t not in out])
    return out + leftovers


def unique_constraints(conn: sqlite3.Connection, table: str) -> list[list[str]]:
    uniques: list[list[str]] = []
    idx_rows = conn.execute(f"PRAGMA index_list({table})").fetchall()

    for idx in idx_rows:
        # SQLite pragma index_list columns: seq, name, unique, origin, partial
        idx_name = idx[1]
        is_unique = idx[2] == 1
        origin = idx[3] if len(idx) > 3 else ""
        if not is_unique or origin == "pk":
            continue

        cols = conn.execute(f"PRAGMA index_info({idx_name})").fetchall()
        col_names = [c[2] for c in cols if c[2]]
        if col_names:
            uniques.append(col_names)

    return uniques


def write_schema_sql(conn: sqlite3.Connection, tables: list[str], out_file: Path):
    lines = [
        "-- Auto-generated from SQLite by scripts/sqlite_to_supabase.py",
        "-- Target: Supabase Postgres",
        "",
        "BEGIN;",
        "",
    ]

    for table in tables:
        cols = conn.execute(f"PRAGMA table_info({table})").fetchall()
        fks = foreign_keys(conn, table)
        uniques = unique_constraints(conn, table)

        lines.append(f"CREATE TABLE IF NOT EXISTS public.{table} (")
        defs = []

        for c in cols:
            # pragma table_info: cid, name, type, notnull, dflt_value, pk
            col_name, col_type, notnull, dflt, pk = c[1], c[2], c[3], c[4], c[5]
            pg_type = map_type(col_name, col_type)
            is_bool = pg_type == "BOOLEAN"

            if pk == 1 and "INT" in (col_type or "").upper():
                defs.append(
                    f"  {col_name} BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY"
                )
                continue

            col_def = f"  {col_name} {pg_type}"
            if notnull:
                col_def += " NOT NULL"

            d = default_expr(dflt, as_boolean=is_bool)
            if d is not None:
                col_def += f" DEFAULT {d}"

            defs.append(col_def)

        for fk in fks:
            fk_line = (
                f"  FOREIGN KEY ({fk['from_col']}) REFERENCES public.{fk['ref_table']}"
                f"({fk['ref_col']})"
            )
            if fk["on_update"] and fk["on_update"].upper() != "NO ACTION":
                fk_line += f" ON UPDATE {fk['on_update']}"
            if fk["on_delete"] and fk["on_delete"].upper() != "NO ACTION":
                fk_line += f" ON DELETE {fk['on_delete']}"
            defs.append(fk_line)

        for cols_unique in uniques:
            defs.append(f"  UNIQUE ({', '.join(cols_unique)})")

        lines.append(",\n".join(defs))
        lines.append(");")
        lines.append("")

    lines.append("COMMIT;")
    lines.append("")
    out_file.write_text("\n".join(lines), encoding="utf-8")


def write_seed_sql(conn: sqlite3.Connection, tables: list[str], out_file: Path):
    lines = [
        "-- Auto-generated from SQLite by scripts/sqlite_to_supabase.py",
        "-- Inserts all existing SQLite rows into Supabase Postgres tables.",
        "",
        "BEGIN;",
        "",
    ]

    identity_cols: list[tuple[str, str]] = []

    for table in tables:
        cols = conn.execute(f"PRAGMA table_info({table})").fetchall()
        col_names = [c[1] for c in cols]
        pg_types = [map_type(c[1], c[2]) for c in cols]

        for c in cols:
            if c[5] == 1 and "INT" in (c[2] or "").upper():
                identity_cols.append((table, c[1]))

        data = conn.execute(f"SELECT * FROM {table}").fetchall()
        if not data:
            continue

        lines.append(f"-- {table}")
        lines.append(f"INSERT INTO public.{table} ({', '.join(col_names)}) VALUES")

        value_rows = []
        for row in data:
            vals = []
            for i, v in enumerate(row):
                vals.append(quote_value(v, as_boolean=(pg_types[i] == "BOOLEAN")))
            value_rows.append(f"  ({', '.join(vals)})")

        lines.append(",\n".join(value_rows) + ";")
        lines.append("")

    for table, col in identity_cols:
        lines.append(
            "SELECT setval("
            f"pg_get_serial_sequence('public.{table}', '{col}'), "
            f"COALESCE((SELECT MAX({col}) FROM public.{table}), 1), true"
            ");"
        )

    lines.append("")
    lines.append("COMMIT;")
    lines.append("")
    out_file.write_text("\n".join(lines), encoding="utf-8")


def main():
    parser = argparse.ArgumentParser(
        description="Export SQLite schema + data to Supabase-friendly SQL files."
    )
    parser.add_argument(
        "--db",
        type=Path,
        default=Path("shop.db"),
        help="Path to source SQLite database (default: shop.db)",
    )
    parser.add_argument(
        "--out",
        type=Path,
        default=Path("supabase"),
        help="Output directory for SQL files (default: supabase/)",
    )
    args = parser.parse_args()

    if not args.db.exists():
        raise SystemExit(f"Database not found: {args.db}")

    args.out.mkdir(parents=True, exist_ok=True)

    conn = sqlite3.connect(str(args.db))
    try:
        tables = ordered_tables(conn, read_tables(conn))
        schema_file = args.out / "01_schema.sql"
        seed_file = args.out / "02_seed.sql"

        write_schema_sql(conn, tables, schema_file)
        write_seed_sql(conn, tables, seed_file)
    finally:
        conn.close()

    print(f"Wrote {schema_file}")
    print(f"Wrote {seed_file}")


if __name__ == "__main__":
    main()
